# Generated by Django 3.0.8 on 2020-10-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=600)),
            ],
        ),
    ]
